selected_competencies = ['support managers',
 'use microsoft office programs',
 'make powerpoint presentations',
 'corporate law',
 'energy market',
 'monitor work site',
 'make independent operating decisions and work independently',
 'assess and manage environmental impact',
 'metallurgy',
 'follow health and safety procedures',
 'manage inventory',
 'perform customer service operations',
 'corrective action and preventive action',
 'procurement legislation and lifecycle',
 'inspect material',
 'organise provide and evaluate training',
 'diving vessels systems',
 'facilities management in the organisation',
 'monitor banking activities',
 'optimise production',
 'business analysis',
 'permit to work systems',
 'personal protective equipment',
 'maintain water infrastructure',
 'perform crane operations',
 'follow procedures to control substances hazardous to health',
 'rigging terminology',
 'operate and maintain drilling equipment',
 'conduct content quality assurance',
 'draw up marketing and sales plan',
 'engage with stakeholders',
 'water policies',
 'monitor water systems',
 'use database management systems',
 'sql',
 'cloud technologies',
 'laboratory information management system',
 'primavera software',
 'liaise with engineers',
 'qgis software',
 'drive large goods vehicles',
 'prerequisite programs procedures',
 'manage process engineering activities',
 'manage quantitative data',
 'geometry',
 'provide mentorship',
 'perform pricing operations',
 'apply numeracy skills',
 'coordinate drilling',
 'read gas meter',
 'bentley microstation software',
 'cost value reconciliation',
 'engineering procurement construction commissioning',
 'tend hoses',
 'power plant equipment',
 'manage electricity transmission systems',
 'ecology and its principles',
 'visualsoft software',
 'design oil wells and well paths',
 'use geographic information systems',
 'measure team performance',
 'maintain computer hardware',
 'conduct cleaning in place',
 'geotechnical engineering',
 'manage transfer pricing documentation',
 'lusas software',
 'cae software',
 'develop and manage website',
 'measure or monitor reservoir volumes',
 'alternative fuels',
 'transport dangerous goods',
 'identify risk of flooding',
 'in vitro diagnosctic regulation',
 'manage inhalation chambers',
 'manage operational budgets',
 'operate dishwashing machine',
 'plan animal breeding programmes',
 'manage payroll',
 'oversee and maintain cleaning equipment',
 'drug administration regulations',
 'extensible markup language',
 'execute email marketing',
 'develop technology strategy',
 'perform marketing management operations',
 'develop with cloud services',
 'maintain and configure ict systems',
 'monitor and adjust fermentation processes',
 'assist in/perform blood sampling',
 'rtx toxin',
 'supervise laboratory operations',
 'operate distillation equipment',
 'laws on the transportation of dangerous goods',
 'in vitro sciences',
 'work in cold environments',
 'drive helicopter',
 'apply teaching strategies',
 'mining engineering',
 'follow reporting procedures',
 'customer relationship management',
 'project management and its principles']
